export const restaurant_data = [
  {
    category: "Italian restaurant",
    companyName: "Ainslie",
    address: "76 Ainsliet, Brooklyn, NY 11211",
    streetAddress: "76 Ainslie St Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11211,
    mobile: "(347) 725-3400",
    website: "http://www.ainsliebk.com/",
    email: "Asset-3@4x-300x300.png",
    rating: 4.3,
    reviewCount: 512,
  },
  {
    category: "Bar & grill",
    companyName: "Teddy's Bar & Grill",
    address: "96 Berry St, Brooklyn, NY 11249",
    streetAddress: "96 Berry St Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11249,
    mobile: "(718) 384-9787",
    website: "https://www.teddys.nyc/",
    email: "info@teddys.nyc",
    rating: 4.5,
    reviewCount: 638,
  },
  {
    category: "Bar",
    companyName: "MIDNIGHTS",
    address: "149 N 6th St, Brooklyn, NY 11249",
    streetAddress: "149 N 6th St Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11249,
    mobile: "(929) 295-8176",
    website: "http://midnightsbk.com/",
    email: "reservations@midnightsbk.com",
    rating: 4.5,
    reviewCount: 336,
  },
  {
    category: "Wine bar",
    companyName: "Sauced",
    address: "331 Bedford Ave, Brooklyn, NY 11211",
    streetAddress: "331 Bedford Ave Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11211,
    mobile: "(347) 695-6286",
    website: "http://saucedbklyn.com/",
    email: null,
    rating: 4.4,
    reviewCount: 81,
  },
  {
    category: "New American restaurant",
    companyName: "Pheasant",
    address: "445 Graham Ave, Brooklyn, NY 11211",
    streetAddress: "445 Graham Ave Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11211,
    mobile: "(718) 675-5588",
    website: "http://www.pheasantnyc.com/",
    email: "eat@pheasantnyc.com",
    rating: 4.6,
    reviewCount: 174,
  },
  {
    category: "Restaurant",
    companyName: "Applebee's Grill + Bar",
    address: "234 W 42nd St, New York, NY 10036",
    streetAddress: "234 W 42nd StNew York",
    city: "New York",
    state: "NY",
    Zip: 10036,
    mobile: "(212) 391-7414",
    website:
      "https://restaurants.applebees.com/en-us/ny/new-york/234-w.-42nd-st.-95017?utm_source=google&utm_medium=organic&utm_campaign=google_my_business&utm_term=95017&utm_content=website",
    email: null,
    rating: 3.7,
    reviewCount: 4596,
  },
  {
    category: "New American restaurant",
    companyName: "Otis",
    address: "18 Harrison Pl, Brooklyn, NY 11206",
    streetAddress: "18 Harrison Pl Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11206,
    mobile: "(646) 886-0601",
    website: "http://www.otisbk.com/",
    email: "11206info@otisbk.com",
    rating: 4.8,
    reviewCount: 545,
  },
  {
    category: "Bagel shop",
    companyName: "Avenue P Appetizers & Bagels",
    address: "466 Avenue P, Brooklyn, NY 11223",
    streetAddress: "466 Avenue P Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11223,
    mobile: "(718) 339-7202",
    website: "https://avepappetizer.com/",
    email: null,
    rating: 4.4,
    reviewCount: 40,
  },
  {
    category: "Bar",
    companyName: "Sweetwater",
    address: "105 N 6th St, Brooklyn, NY 11211",
    streetAddress: "105 N 6th St Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11211,
    mobile: "(718) 963-0608",
    website: "http://www.sweetwaterny.com/",
    email: "11pmContact718-963-0608info@sweetwaterny.com",
    rating: 4.5,
    reviewCount: 521,
  },
  {
    category: "Bar",
    companyName: "Tuffet",
    address: "286 Graham Ave, Brooklyn, NY 11211",
    streetAddress: "286 Graham Ave Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11211,
    mobile: "(718) 388-7434",
    website: "http://www.tuffetnyc.com/",
    email: "contact@tuffetnyc.om",
    rating: 4.5,
    reviewCount: 107,
  },
  {
    category: "Northern Italian restaurant",
    companyName: "Testo",
    address: "141 Leonard St, Brooklyn, NY 11206",
    streetAddress: "141 Leonard St Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11206,
    mobile: "(718) 388-4810",
    website: "http://www.testobrooklyn.com/",
    email: null,
    rating: 4.6,
    reviewCount: 291,
  },
  {
    category: "Bar",
    companyName: "Easy Lover",
    address: "790 Metropolitan Ave, Brooklyn, NY 11211",
    streetAddress: "790 Metropolitan Ave Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11211,
    mobile: null,
    website: "http://easyloverbar.com/",
    email: "605a7baede844d278b89dc95ae0a9123@sentry-next.wixpress.com",
    rating: 4.5,
    reviewCount: 116,
  },
  {
    category: "Bar",
    companyName: "Concrete",
    address: "906 Broadway, Brooklyn, NY 11206",
    streetAddress: "906 BroadwayBrooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11206,
    mobile: "(917) 966-8440",
    website: "http://concrete-brooklyn.com/",
    email: "906broadway@gmail.com",
    rating: 4.5,
    reviewCount: 211,
  },
  {
    category: "Pizza restaurant",
    companyName: "Pizzette",
    address: "191 Graham Ave, Brooklyn, NY 11206",
    streetAddress: "191 Graham Ave Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11206,
    mobile: "(917) 909-1555",
    website: "http://pizzettebk.com/",
    email: "pizzettellc@gmail.com",
    rating: 4.4,
    reviewCount: 85,
  },
  {
    category: "Bar",
    companyName: "The Richardson",
    address: "451 Graham Ave, Brooklyn, NY 11222",
    streetAddress: "451 Graham Ave Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11222,
    mobile: "(718) 389-0839",
    website: "http://www.therichardsonnyc.com/",
    email: "themissfires@gmail.com",
    rating: 4.3,
    reviewCount: 232,
  },
  {
    category: "Bar",
    companyName: "Gertie",
    address: "357 Grand St, Brooklyn, NY 11211",
    streetAddress: "357 Grand St Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11211,
    mobile: "(718) 636-0902",
    website: "https://www.gertie.nyc/",
    email: "hello@gertie.nyc",
    rating: 4.4,
    reviewCount: 265,
  },
  {
    category: "Wine bar",
    companyName: "Have & Meyer",
    address: "103 Havemeyer St, Brooklyn, NY 11211",
    streetAddress: "103 Havemeyer St Brooklyn",
    city: "Brooklyn",
    state: "NY",
    Zip: 11211,
    mobile: "(718) 419-0722",
    website: "http://haveandmeyer.com/",
    email: "moc.reyemdnaevah@ofni.Privacy",
    rating: 4.4,
    reviewCount: 317,
  },
];
